config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :docs
  root 'docs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  has_attached_file :pdf, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pdf, {:content_type => %w(image/jpeg image/jpg image/png application/pdf "video/mp4", "video.mov", "video/mpeg","video/mpeg4", application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  
  def index
    @docs = Doc.all.order("created_at DESC")
  end
  
  def new
    @doc = Doc.new
  end
  
  def create
    @doc = Doc.new(doc_params)
    if @doc.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def show
    @doc = Doc.find(params[:id])
  end
  
  private
    
    def doc_params
      params.require(:doc).permit(:title, :description, :pdf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
<%= f.file_field :pdf %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.button :submit %>
<% end %>

app/views/docs/index.html.erb
<div class="container">
<h1>What People Are Reading</h1>
<hr>
<% @docs.each do |doc| %>
	<p><%= link_to doc.title, doc_path(doc) %></p>
	<hr>
<% end %>


</div>

app/views/docs/new.html.erb
<div class="container">
<h1>Upload</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>
</div>

app/views/docs/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-7">
<iframe src=<%= @doc.pdf %> width="600" height="780" style="border: none;"> </iframe>
</div>

<div class="col-md-4">
<h1><%= @doc.title %></h1>
<p>Upload date: <%= @doc.created_at.localtime %></p>
<p>File name: <%= @doc.pdf_file_name %></p>
<p>Size: <%= @doc.pdf_file_size / 1024 %> KB</p>

<p><%= @doc.description %></p>
<p><%= link_to "Download", @doc.pdf.url, class:"btn btn-success" %></p>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Scribd Lite", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">

            <%= link_to "Upload", new_doc_path, class: "btn btn-primary navbar-btn" %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="container">
    <%= yield %>
	</div>
  </body>
</html>